# Site settings
title: "Bakker Technologies"
description: "Information about Bakker Technologies"
baseurl: ""
url: "https://bakkertechnologies.no"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
github: [metadata]
