# Site settings
title: "Bakker Technologies"
description: "Information about Bakker Technologies"
baseurl: "/info.bakkertechnologies.no"
url: "https://haakonbakker.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# GitHub Pages settings
github: [metadata]
